// <auto-generated />
using LocalBusinessApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalBusinessApi.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20230818214122_AddUsers")]
    partial class AddUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Rating")
                        .HasColumnType("longtext");

                    b.Property<string>("RestaurantCity")
                        .HasColumnType("longtext");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("longtext");

                    b.Property<string>("Review")
                        .HasColumnType("longtext");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Rating = "8",
                            RestaurantCity = "Portland",
                            RestaurantName = "RedWood",
                            Review = "Great breakFast Place"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Rating = "9",
                            RestaurantCity = "San Francisco",
                            RestaurantName = "Woods Man",
                            Review = "best seafood in town"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Rating = "7",
                            RestaurantCity = "Seatle",
                            RestaurantName = "Wayan",
                            Review = "If you are loking for full bar this is the pplace for you"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Rating = "6",
                            RestaurantCity = "Portland",
                            RestaurantName = "Sweet Basil",
                            Review = "Great Thai food and fast service"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Rating = "10",
                            RestaurantCity = "Vancouver",
                            RestaurantName = "Tap & Barrel",
                            Review = "Awesome beer and great view of the harbor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
